FROM golang:1.15 AS builder
RUN mkdir /distributing
WORKDIR /distributing
COPY notify/ notify/
COPY pomo/ pomo/
WORKDIR /distributing/pomo
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -tags=containers
# this image is a linux provision that has no users of direcotries
FROM scratch 
WORKDIR /
COPY --from=builder /distributing/pomo/pomo .
CMD ["/pomo"]